### ISSUE TITLE
Why my recollectr open with blank screen?

### ISSUE THREAD

**Issue by physicsLoveJava** [Recollectr/releases#1]
![image](https://user-images.githubusercontent.com/9126374/56590453-b6498d80-6619-11e9-8f2b-6f532a0f823c.png)

I don't know why, yesterday everything is alright.

**Comment by Recollectr** [comment]
@physicsLoveJava

**Comment by Recollectr** [comment]
Hi @physicsLoveJava. Sorry that we didn't get back to you sooner on this, and sorry for this issue you're seeing too. We haven't been expecting issues on GitHub as we've been handling support requests at (support@recollectr.io) or Reddit at https://reddit.com/r/Recollectr. We should have disabled issues here or updated the issue template.

It's hard to say exactly what the issue might be just based on the screenshot, but in the handful of cases users run into trouble starting Recollectr, it's usually because Recollectr was interrupted or otherwise failed to save its most recent state properly when exiting.

Recollectr creates backups on startup and once every 12 hours, and restoring one of these backups should resolve the issue and get you up and running again. [You can find your backups and how to restore them on  this page.](https://recollectr.io/help/docs/desktop/troubleshooting/)

Note than if you don't have syncing enabled in Recollectr, you might be set back by up to 12 hours.

Sorry again for the trouble this has caused you. Let us know how you make out and if things still aren't working we'll find out what's going on and get you back up and running.

If you can send the Recollectr log file to us for analysis, we can try to find out what's going on and remedy the issue so no else sees it in the future. [See this page for your log file location.](https://recollectr.io/help/docs/desktop/technical/)

Hope this helps!

**Comment by physicsLoveJava** [comment]
[log.log](https://github.com/Recollectr/releases/files/3119309/log.log) this is my recollectr log
I used the backup method, it didn't work for me, just as the same blank screen.

**Comment by Recollectr** [comment]
I'm really sorry to hear you're still having trouble! 

We had a chance to take a look at your log file and it looks like the backup you restored is invalid JSON. When Recollectr makes backups at startup, it doesn't check that the file it's backing up is valid, it just copies it as is. This means some of your backups can be invalid, and that new invalid backups can be created on startup.

This line in your log file indicates that the `state.json` file you tried last wasn't valid JSON:

```
[2019-04-26 07:57:37.831] [error] State file valid: false
```

It's possible that a write operation was interrupted and that your most recent valid backup might look okay at first glance. After checking that the file isn't 0kb in size, check to make sure the file is valid JSON. Interrupted writes might manifest as invalid or garbage characters at the end of your file, or an incomplete file.

Going back a bit further in your backups should definitely resolve the issue. Sorry again for the trouble this has caused.

**Comment by physicsLoveJava** [comment]
Thank you for your help! My recollectr pop up a release note when I start my computer, And it's become good now.

**Comment by physicsLoveJava** [comment]
I close my issue

**Comment by Recollectr** [comment]
@physicsLoveJava I'm glad to hear everything's working properly again!

If you ever have any issues we'll always be here to help!
